In [15]:
from skimage.segmentation import find_boundaries
import numpy as np
mask = np.array(
    [
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],  # Row 0
        [0, 1, 1, 1, 0, 0, 2, 2, 2, 0],  # Row 1
        [0, 1, 0, 1, 0, 0, 2, 2, 2, 0],  # Row 2
        [0, 1, 1, 1, 0, 0, 2, 2, 2, 0],  # Row 3
        [0, 0, 0, 0, 3, 3, 3, 0, 0, 0],  # Row 4
        [0, 0, 0, 0, 3, 3, 3, 0, 4, 0],  # Row 5
        [0, 0, 0, 0, 3, 3, 3, 0, 4, 0],  # Row 6
        [0, 0, 5, 5, 5, 0, 0, 0, 4, 0],  # Row 7
        [0, 0, 5, 5, 5, 0, 0, 0, 4, 0],  # Row 8
        [0, 0, 5, 5, 5, 0, 0, 0, 0, 0],  # Row 9
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],  # Row 10
    ]
)
boundary = find_boundaries(mask.astype(np.uint8), mode="inner", connectivity=1)
boundary

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True, False, False,  True,  True,  True,
        False],
       [False,  True, False,  True, False, False,  True, False,  True,
        False],
       [False,  True,  True,  True, False, False,  True,  True,  True,
        False],
       [False, False, False, False,  True,  True,  True, False, False,
        False],
       [False, False, False, False,  True, False,  True, False,  True,
        False],
       [False, False, False, False,  True,  True,  True, False,  True,
        False],
       [False, False,  True,  True,  True, False, False, False,  True,
        False],
       [False, False,  True, False,  True, False, False, False,  True,
        False],
       [False, False,  True,  True,  True, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [16]:
from skimage.segmentation import find_boundaries
import numpy as np
mask = np.array(
    [
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],  # Row 0
        [0, 1, 1, 1, 0, 0, 2, 2, 2, 0],  # Row 1
        [0, 1, 0, 1, 0, 0, 2, 2, 2, 0],  # Row 2
        [0, 1, 1, 1, 0, 0, 2, 2, 2, 0],  # Row 3
        [0, 0, 0, 0, 3, 3, 3, 0, 0, 0],  # Row 4
        [0, 0, 0, 0, 3, 3, 3, 0, 4, 0],  # Row 5
        [0, 0, 0, 0, 3, 3, 3, 0, 4, 0],  # Row 6
        [0, 0, 5, 5, 5, 0, 0, 0, 4, 0],  # Row 7
        [0, 0, 5, 5, 5, 0, 0, 0, 4, 0],  # Row 8
        [0, 0, 5, 5, 5, 0, 0, 0, 0, 0],  # Row 9
    ]
)
boundary = find_boundaries(mask.astype(np.uint8), mode="inner", connectivity=1)
boundary

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True, False, False,  True,  True,  True,
        False],
       [False,  True, False,  True, False, False,  True, False,  True,
        False],
       [False,  True,  True,  True, False, False,  True,  True,  True,
        False],
       [False, False, False, False,  True,  True,  True, False, False,
        False],
       [False, False, False, False,  True, False,  True, False,  True,
        False],
       [False, False, False, False,  True,  True,  True, False,  True,
        False],
       [False, False,  True,  True,  True, False, False, False,  True,
        False],
       [False, False,  True, False,  True, False, False, False,  True,
        False],
       [False, False,  True, False,  True, False, False, False, False,
        False]])

In [17]:
from skimage.segmentation import find_boundaries
import numpy as np
mask = np.array(
    [
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],  # Row 0
        [0, 1, 1, 1, 0, 0, 2, 2, 2, 0],  # Row 1
        [0, 1, 0, 1, 0, 0, 2, 2, 2, 0],  # Row 2
        [0, 1, 1, 1, 0, 0, 2, 2, 2, 0],  # Row 3
        [0, 0, 0, 0, 3, 3, 3, 0, 0, 0],  # Row 4
        [0, 0, 0, 0, 3, 3, 3, 0, 4, 0],  # Row 5
        [0, 0, 0, 0, 3, 3, 3, 0, 4, 0],  # Row 6
        [0, 5, 5, 5, 5, 0, 0, 0, 4, 0],  # Row 7
        [0, 5, 5, 5, 5, 0, 0, 0, 4, 0],  # Row 8
        [0, 5, 5, 5, 5, 0, 0, 0, 0, 0],  # Row 9
    ]
)
boundary = find_boundaries(mask.astype(np.uint8), mode="inner", connectivity=1)
boundary

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True, False, False,  True,  True,  True,
        False],
       [False,  True, False,  True, False, False,  True, False,  True,
        False],
       [False,  True,  True,  True, False, False,  True,  True,  True,
        False],
       [False, False, False, False,  True,  True,  True, False, False,
        False],
       [False, False, False, False,  True, False,  True, False,  True,
        False],
       [False, False, False, False,  True,  True,  True, False,  True,
        False],
       [False,  True,  True,  True,  True, False, False, False,  True,
        False],
       [False,  True, False, False,  True, False, False, False,  True,
        False],
       [False,  True, False, False,  True, False, False, False, False,
        False]])

In [21]:
boundary.astype(int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
       [0, 1, 0, 1, 0, 0, 1, 0, 1, 0],
       [0, 1, 1, 1, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 1, 1, 1, 0, 1, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 0]])

In [7]:
def _get_indexed_mask(mask: np.ndarray, boundary: np.ndarray) -> np.ndarray:
    """
    Convert a boundary mask into an indexed mask with the same cell identifiers.

    Args:
        mask (np.ndarray): Original mask with cell identifiers.
        boundary (np.ndarray): Binary boundary mask.

    Returns:
        np.ndarray: Indexed boundary mask.
    """
    boundary = boundary.astype(int)
    boundary_loc = np.where(boundary == 1)
    boundary[boundary_loc] = mask[boundary_loc]
    return boundary

In [9]:
_get_indexed_mask(mask, boundary)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 2, 2, 2, 0],
       [0, 1, 0, 1, 0, 0, 2, 0, 2, 0],
       [0, 1, 1, 1, 0, 0, 2, 2, 2, 0],
       [0, 0, 0, 0, 3, 3, 3, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 3, 0, 4, 0],
       [0, 0, 0, 0, 3, 3, 3, 0, 4, 0],
       [0, 0, 5, 5, 5, 0, 0, 0, 4, 0],
       [0, 0, 5, 0, 5, 0, 0, 0, 4, 0],
       [0, 0, 5, 5, 5, 0, 0, 0, 0, 0]])

In [12]:
# Expected boundary mask
expected_boundary = np.zeros_like(mask)

# Object 1 boundary (label 1)
expected_boundary[1, 1] = 1
expected_boundary[1, 2] = 1
expected_boundary[1, 3] = 1
expected_boundary[2, 1] = 1
expected_boundary[2, 3] = 1
expected_boundary[3, 1] = 1
expected_boundary[3, 2] = 1
expected_boundary[3, 3] = 1

# Object 2 boundary (label 2)
expected_boundary[1, 6] = 2
expected_boundary[1, 7] = 2
expected_boundary[1, 8] = 2
expected_boundary[2, 6] = 2
expected_boundary[2, 8] = 2
expected_boundary[3, 6] = 2
expected_boundary[3, 7] = 2
expected_boundary[3, 8] = 2

# Object 3 boundary (label 3)
expected_boundary[4, 4] = 3
expected_boundary[4, 5] = 3
expected_boundary[4, 6] = 3
expected_boundary[5, 4] = 3
expected_boundary[5, 6] = 3
expected_boundary[6, 4] = 3
expected_boundary[6, 5] = 3
expected_boundary[6, 6] = 3

# Object 4 boundary (label 4)
expected_boundary[5, 8] = 4
expected_boundary[6, 8] = 4
expected_boundary[7, 8] = 4
expected_boundary[8, 8] = 4

# Object 5 boundary (label 5)
expected_boundary[7, 2] = 5
expected_boundary[7, 3] = 5
expected_boundary[7, 4] = 5
expected_boundary[8, 2] = 5
expected_boundary[8, 4] = 5
expected_boundary[9, 2] = 5
expected_boundary[9, 3] = 5
expected_boundary[9, 4] = 5

expected_boundary

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 2, 2, 2, 0],
       [0, 1, 0, 1, 0, 0, 2, 0, 2, 0],
       [0, 1, 1, 1, 0, 0, 2, 2, 2, 0],
       [0, 0, 0, 0, 3, 3, 3, 0, 0, 0],
       [0, 0, 0, 0, 3, 0, 3, 0, 4, 0],
       [0, 0, 0, 0, 3, 3, 3, 0, 4, 0],
       [0, 0, 5, 5, 5, 0, 0, 0, 4, 0],
       [0, 0, 5, 0, 5, 0, 0, 0, 4, 0],
       [0, 0, 5, 5, 5, 0, 0, 0, 0, 0]])

In [13]:
np.testing.assert_array_equal(mask, expected_boundary)

AssertionError: 
Arrays are not equal

Mismatched elements: 2 / 100 (2%)
Max absolute difference: 3
Max relative difference: 0.
 x: array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 2, 2, 2, 0],
       [0, 1, 1, 1, 0, 0, 2, 0, 2, 0],...
 y: array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 2, 2, 2, 0],
       [0, 1, 0, 1, 0, 0, 2, 0, 2, 0],...

In [14]:
mask

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 2, 2, 2, 0],
       [0, 1, 1, 1, 0, 0, 2, 0, 2, 0],
       [0, 1, 1, 1, 0, 0, 2, 2, 2, 0],
       [0, 0, 0, 0, 3, 3, 3, 0, 0, 0],
       [0, 0, 0, 0, 3, 3, 3, 0, 4, 0],
       [0, 0, 0, 0, 3, 3, 3, 0, 4, 0],
       [0, 0, 5, 5, 5, 0, 0, 0, 4, 0],
       [0, 0, 5, 0, 5, 0, 0, 0, 4, 0],
       [0, 0, 5, 5, 5, 0, 0, 0, 0, 0]])